# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-04-13 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170212_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='fav_animal',
            new_name='preferred_foot',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='hobby',
            new_name='preferred_position',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='dob',
        ),
    ]
